server:
  port: 8080
spring:
  application:
    name: gateway
  profiles:
    active: dev
zuul:
  routes:
    api-index:
      path: /api/index/**
      serviceId: index
    api-upload:
      path: /api/upload/**
      serviceId: upload
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
